<a href="https://colab.research.google.com/github/KirPim/DS_school_2020_home_work/blob/main/HW6_lesson_7_tasks_2_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

#Решение


__2)__ $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$, $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} =   
\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$

$AB = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} =   
\begin{pmatrix}
4+0 & -1-10\\ 
12+0 & -3+0
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}
$

In [ ]:
#Проверка
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A + B}')
print(f'Матрица AB\n{A@B}')


Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3)__ $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=
3\cdot\begin{pmatrix} 1 & 7\\3 & -6\end{pmatrix}
-2\cdot\begin{pmatrix}0 & 5\\2 & -1\end{pmatrix}
+4\cdot\begin{pmatrix}2 & -4\\1 & 1\end{pmatrix}
=\begin{pmatrix}3 & 21\\9 & -18\end{pmatrix}
+\begin{pmatrix}0 & -10\\-4 & 2\end{pmatrix}
+\begin{pmatrix}8 & -16\\4 & 4\end{pmatrix}
=\begin{pmatrix}11 & -5\\9 & -12\end{pmatrix}
$

In [ ]:
#Проверка
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{C}')
print(f'3A-2B+4C=\n{3 * A - 2 * B + 4 * C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 2 -4]
 [ 1  1]]
3A-2B+4C=
[[ 11  -5]
 [  9 -12]]


__4)__ $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.

$AA^{T}=
\begin{pmatrix}4 & 1\\5 & -2\\2 & 3\end{pmatrix}
\cdot
\begin{pmatrix}4 & 5 & 2\\1 & -2 & 3\end{pmatrix}
=
\begin{pmatrix}16+1 & 20-2 & 8+3
\\20-2 & 25+4 & 10-6
\\8+3 & 10-6 & 4+9\end{pmatrix}
=
\begin{pmatrix}17 & 18 & 11\\18 & 29 & 4\\11 & 4 & 13\end{pmatrix}
$

$A^{T}A=
\begin{pmatrix}4 & 5 & 2\\1 & -2 & 3\end{pmatrix}
\cdot
\begin{pmatrix}4 & 1\\5 & -2\\2 & 3\end{pmatrix}
=
\begin{pmatrix}16+25+4 & 4-10+6\\4-10+6 & 1+4+9\end{pmatrix}
=
\begin{pmatrix}45 & 0\\0 & 14\end{pmatrix}
$

In [ ]:
#Проверка
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')
print(f'A(AT)=\n{A @ A.T}')
print(f'(AT)A=\n{A.T @ A}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
A(AT)=
[[17 18 11]
 [18 29  4]
 [11  4 13]]
(AT)A=
[[45  0]
 [ 0 14]]


__5*)__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def matrix_comp(a, b):
  m = len(a)
  n = len(b[0])
  p = len(b)
  
  c = [[0 for j in range(n)] for i in range(m)]
  summa = 0

  for i in range(m):
    for j in range(n):
      summa = 0
      for k in range(p):
        summa += a[i][k] * b[k][j]
        c[i][j] = summa        
  return c

#Проверка

a = [[4, 1], [5, -2], [2, 3]]
b = [[4, 5, 2], [1, -2, 3]]
matrix_comp(a, b)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

__6)__ Вычислить определитель:

a)
$\begin{vmatrix} sinx & -cosx\\cosx & sinx\end{vmatrix}
=sin^{2}x + cos^{2}x = 1
$

б)
$\begin{vmatrix} 8 & 4 & 6\\0 & 5 & 1\\0 & 0 & 9\end{vmatrix}
=8\cdot\begin{vmatrix} 5 & 1\\0 & 9\end{vmatrix}
-4\cdot\begin{vmatrix} 0 & 1\\0 & 9\end{vmatrix} 
+6\cdot\begin{vmatrix} 0 & 5\\0 & 0\end{vmatrix}
=8\cdot(5\cdot9-0\cdot1)-4\cdot(0\cdot9-0\cdot1)+6\cdot(0\cdot0-0\cdot5)
=8\cdot45-4\cdot0+6\cdot0
=360
$
    
в)
$\begin{vmatrix} 2 & 3 & 4\\5 & 6 & 7\\8 & 9 & 10\end{vmatrix}
=2\cdot\begin{vmatrix} 6 & 7\\9 & 10\end{vmatrix}
-3\cdot\begin{vmatrix} 5 & 7\\8 & 10\end{vmatrix} 
+4\cdot\begin{vmatrix} 5 & 6\\8 & 9\end{vmatrix}
=2\cdot(6\cdot10-9\cdot7)-3\cdot(5\cdot10-8\cdot7)+4\cdot(5\cdot9-8\cdot6)
=2\cdot(-3)-3\cdot(-6)+4\cdot(-3)
=0
$

In [ ]:
#Проверка

A2 = np.array([[8, 4, 6], [0, 5, 1], [0, 0, 9]])
A3 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])

print(f'Матрица A2:\n{A2}')
print(f'Определитель A2:\n{np.linalg.det(A2):.0f}')
print(f'Матрица A3:\n{A3}')
print(f'Определитель A3:\n{np.linalg.det(A3):.0f}')

Матрица A2:
[[8 4 6]
 [0 5 1]
 [0 0 9]]
Определитель A2:
360
Матрица A3:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Определитель A3:
0


__7)__ $det(A)=4$

   а) $det(A^{2})=det(AA)=det(A)\cdot det(A)=4\cdot4=16$;
    
   б) $det(A^{T})=det(A)=4$;
    
   в) $det(2A)=2^n\cdot det(A)=2^n\cdot4=2^{n+2}$, где $n$ - порядок матрицы

In [ ]:
#Проверка

A = np.array([[3, 2], [1, 2]])

print(f'Матрица A:{A}')
print(f'Определитель A={np.linalg.det(A):.0f}')
print(f'Определитель A^2={np.linalg.det(A @ A):.0f}')
print(f'Определитель AT={np.linalg.det(A.T):.0f}')
print(f'Определитель 2A={np.linalg.det(2 * A):.0f}')

Матрица A:[[3 2]
 [1 2]]
Определитель A=4
Определитель A^2=16
Определитель AT=4
Определитель 2A=16


__8)__  $A=\begin{pmatrix} -2 & 7 & -3\\4 & -14 & 6\\-3 & 7 & 13\end{pmatrix}$

$$det(A)=\begin{vmatrix} -2 & 7 & -3\\4 & -14 & 6\\-3 & 7 & 13\end{vmatrix}
=-2\cdot \begin{vmatrix} -2 & 7 & -3\\-2 & 7 & -3\\-3 & 7 & 13\end{vmatrix}
=-2\cdot \begin{vmatrix} 0 & 0 & 0\\-2 & 7 & -3\\-3 & 7 & 13\end{vmatrix}
=-2\cdot 0\cdot \begin{vmatrix} 7 & -3\\7 & 13\end{vmatrix}
+2\cdot 0\cdot \begin{vmatrix} -2 & -3\\-3 & 13\end{vmatrix}
-2\cdot 0\cdot \begin{vmatrix} -2 & 7\\-3 & 7\end{vmatrix}
=0
$$ 
=> матрица $A$ вырожденная

In [ ]:
#Проверка

A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'Матрица A:\n{A}')
print(f'\nОпределитель A={np.linalg.det(A):.0f}')

Матрица A:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]

Определитель A=0


__9)__ Найти ранг матрицы:

а) $\begin{pmatrix} 1 & 2 & 3\\1 & 1 & 1\\2 & 3 & 4\end{pmatrix}
-> \begin{pmatrix} 1 & 2 & 3\\1 & 1 & 1\\1 & 2 & 3\end{pmatrix}
-> \begin{pmatrix} 1 & 2 & 3\\1 & 1 & 1\\1 & 2 & 3\end{pmatrix}
-> \begin{pmatrix} 1 & 2 & 3\\1 & 1 & 1\end{pmatrix}
-> \begin{pmatrix} 0 & 1 & 2\\1 & 1 & 1\end{pmatrix}
-> R=2
$

б) $\begin{pmatrix} 0 & 0 & 2 & 1\\0 & 0 & 2 & 2
\\0 & 0 & 4 & 3\\2 & 3 & 5 & 6\end{pmatrix}
-> \begin{pmatrix} 0 & 2 & 1\\0 & 2 & 2\\0 & 4 & 3\\3 & 5 & 6\end{pmatrix}
-> \begin{pmatrix} 0 & 1 & 1\\0 & 0 & 2\\0 & 1 & 3\\3 & -1 & 6\end{pmatrix}
-> \begin{pmatrix} 0 & 1 & 1\\0 & 0 & 2\\0 & 1 & 3\\3 & 0 & 9\end{pmatrix}
-> \begin{pmatrix} 0 & 1 & 1\\0 & 0 & 2\\0 & 1 & 3\\3 & 0 & 0\end{pmatrix}
-> \begin{pmatrix} 0 & 1 & -2\\0 & 0 & 2\\0 & 1 & 0\\3 & 0 & 0\end{pmatrix}
-> \begin{pmatrix} 0 & 1 & 0\\0 & 0 & 2\\0 & 1 & 0\\3 & 0 & 0\end{pmatrix}
-> \begin{pmatrix} 0 & 0 & 2\\0 & 1 & 0\\3 & 0 & 0\end{pmatrix}
-> R=3
$

In [ ]:
#Проверка

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'Матрица A:\n{A}')
print(f'Ранг матрицы A = {np.linalg.matrix_rank(A)}')
print(f'Матрица B:\n{B}')
print(f'Ранг матрицы B = {np.linalg.matrix_rank(B)}')

Матрица A:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы A = 2
Матрица B:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы B = 3
